import React from 'react';

const PrivacyPolicy = () => {
    return (
        <main className="container mx-auto p-6">
            <h1 className="text-2xl font-bold mb-4">Privacy Policy</h1>
            <p className="mb-2">Last updated: December 31, 2024</p>
            <p className="mb-4">
                This Privacy Policy describes Our policies and procedures on the collection, use, and
                disclosure of Your information when You use the Service and tells You about Your privacy
                rights and how the law protects You.
            </p>
            <p className="mb-4">
                We use Your Personal data to provide and improve the Service. By using the Service, You
                agree to the collection and use of information in accordance with this Privacy Policy. This
                Privacy Policy has been created with the help of the{' '}
                <a
                    href="https://www.termsfeed.com/privacy-policy-generator/"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-blue-600 hover:underline"
                >
                    Privacy Policy Generator
                </a>
                .
            </p>

            <section className="mb-8">
                <h2 className="text-xl font-semibold mb-4">Interpretation and Definitions</h2>
                <h3 className="text-lg font-medium mb-2">Interpretation</h3>
                <p className="mb-4">
                    The words of which the initial letter is capitalized have meanings defined under the
                    following conditions. The following definitions shall have the same meaning regardless of
                    whether they appear in singular or in plural.
                </p>

                <h3 className="text-lg font-medium mb-2">Definitions</h3>
                <p className="mb-4">For the purposes of this Privacy Policy:</p>
                <ul className="list-disc pl-6 mb-4">
                    <li className="mb-2">
                        <strong>Account:</strong> A unique account created for You to access our Service or
                        parts of our Service.
                    </li>
                    <li className="mb-2">
                        <strong>Affiliate:</strong> An entity that controls, is controlled by, or is under
                        common control with a party, where &quot;control&quot; means ownership of 50% or more of the
                        shares, equity interest, or other securities entitled to vote for election of directors
                        or other managing authority.
                    </li>
                    <li className="mb-2">
                        <strong>Company:</strong> (referred to as either &quot;the Company,&quot; &quot;We,&quot; &quot;Us,&quot; or &quot;Our&quot; in
                        this Agreement) refers to uttoradhikar.
                    </li>
                    <li className="mb-2">
                        <strong>Cookies:</strong> Small files placed on Your computer, mobile device, or any
                        other device by a website, containing details of Your browsing history on that website.
                    </li>
                    <li className="mb-2">
                        <strong>Country:</strong> Refers to: Bangladesh.
                    </li>
                    <li className="mb-2">
                        <strong>Device:</strong> Any device that can access the Service such as a computer, a
                        cellphone, or a digital tablet.
                    </li>
                    <li className="mb-2">
                        <strong>Personal Data:</strong> Any information that relates to an identified or
                        identifiable individual.
                    </li>
                    <li className="mb-2">
                        <strong>Service:</strong> Refers to the Website.
                    </li>
                    <li className="mb-2">
                        <strong>Service Provider:</strong> Any natural or legal person who processes the data on
                        behalf of the Company. It refers to third-party companies or individuals employed by the
                        Company to facilitate the Service, to provide the Service on behalf of the Company, to
                        perform services related to the Service, or to assist the Company in analyzing how the
                        Service is used.
                    </li>
                    <li className="mb-2">
                        <strong>Usage Data:</strong> Data collected automatically, either generated by the use
                        of the Service or from the Service infrastructure itself (e.g., the duration of a page
                        visit).
                    </li>
                    <li className="mb-2">
                        <strong>Website:</strong> Refers to uttoradhikar, accessible from{' '}
                        <a
                            href="https://uttoradhikar.org/"
                            rel="noopener noreferrer"
                            target="_blank"
                            className="text-blue-600 hover:underline"
                        >
                            https://uttoradhikar.org/
                        </a>
                        .
                    </li>
                    <li>
                        <strong>You:</strong> The individual accessing or using the Service, or the company or
                        other legal entity on behalf of which such individual is accessing or using the Service.
                    </li>
                </ul>
            </section>

            <section className="mb-8">
                <h2 className="text-xl font-semibold mb-4">Collecting and Using Your Personal Data</h2>
                <h3 className="text-lg font-medium mb-2">Types of Data Collected</h3>
                <h4 className="text-md font-semibold mb-2">Personal Data</h4>
                <p className="mb-4">
                    While using Our Service, We may ask You to provide Us with certain personally identifiable
                    information that can be used to contact or identify You. Personally identifiable
                    information may include, but is not limited to:
                </p>
                <ul className="list-disc pl-6">
                    <li>Email address</li>
                    <li>First name and last name</li>
                    <li>Usage Data</li>
                </ul>
            </section>
        </main>
    );
};

export default PrivacyPolicy;
